### PR TITLE
Updated for High Isle, Galen, PTS API101038

### PR DESCRIPTION
**Pull request by IsJustaGhost**
Updated the GeoData for up to PTS API101038

### CODE REVIEW

**Comment by IsJustaGhost** [comment]
There are several zones I left out of the geodata since I have yet to be able to get my BeamMeUp plugin from showing the PTS zones in my BeamMeUp plugin test list.

**Comment by Baertram** [comment]
@IsJustaGhost  Is this version compatible with current live server too? Or do I need to waith with the update on esoui.com until Necrom is live?

**Comment by IsJustaGhost** [comment]
Since it's just data in a table retrieved by [zoneId][parentZoneId], It shouldn't really matter. 
The changes to libZone.lua were just to simply adding new entries do the geoDataTable, using only 1 table entry instead of 2. It was to make it easier to convert the date from the debug table in the SV with a single regex. 
Also, I removed it's ability to import the data, dynamically generated in the savedVars that was self verified, since I found it would cause errors before this single line change. With this change, it would return a string instead of the number needed so, it will not work at all. 

I just wish there was an easier way, in game, to get the exact location of the point of entry to a zone transition.
Not all zones are linked to the parent zone their map pin is on. I mean, GetParentZoneId() may return the main zone the dlc came with instead of where zos put the place to enter the zone. Also, the mismatching of zone names and poi names. Making it impossible to do a name match lookup.

**Comment by Baertram** [comment]
Okay, thanks for the exaplanation. So you have tested that changes with your addon(s) and it's okay?
I'll test the overal version on live a few days then and see if the other LibZone part got any issues (which we don't expect).

**Pull request merged**
